import type {
  Activity,
  AuditLog,
  Candidate,
  EmployerRequest,
  NotificationItem,
} from '@/lib/types';

export const candidates: Candidate[] = [
  {
    id: 'CAND-1024',
    name: 'Marcus Chen',
    email: 'marcus.chen@email.com',
    phone: '+86 138 1234 5678',
    country: 'China',
    avatarColor: 'bg-sky-500',
    occupation: 'Senior Welder',
    skills: ['MIG Welding', 'TIG Welding', 'Structural Steel', 'Pipeline'],
    experienceYears: 9,
    education: 'Diploma in Industrial Welding',
    certifications: ['AWS Certified Welder', 'ASME IX'],
    status: 'pending',
    aiStatus: 'completed',
    caseStatus: 'admin_review',
    registeredAt: '2026-06-14T09:23:00Z',
    redactedVisible: false,
    aiExtracted: {
      occupation: 'Welder (First Class)',
      anzscoCode: '322313',
      anzscoTitle: 'Welder',
      summary:
        'Highly skilled structural welder with 9 years of industrial experience across construction and pipeline sectors. Demonstrated proficiency in MIG, TIG, and arc welding techniques. Holds AWS certification and has worked on large-scale infrastructure projects exceeding $2M in value.',
      redactedSummary:
        'Experienced welder with industry-recognized certification and 9+ years in structural and pipeline construction. Demonstrated proficiency in multiple welding techniques. Worked on large-scale infrastructure projects.',
      confidenceScore: 94,
      processedAt: '2026-06-14T10:05:00Z',
      extractedNames: ['Marcus Chen'],
      skills: [
        { name: 'MIG Welding', years: 9, proficiency: 'expert' },
        { name: 'TIG Welding', years: 7, proficiency: 'advanced' },
        { name: 'Structural Steel', years: 9, proficiency: 'expert' },
        { name: 'Pipeline Welding', years: 6, proficiency: 'advanced' },
        { name: 'Arc Welding', years: 9, proficiency: 'expert' },
      ],
      experience: [
        {
          company: 'Shanghai Construction Group',
          role: 'Senior Welder',
          duration: '6 years',
          startDate: '2020-03',
          endDate: 'Present',
          description:
            'Lead welder on infrastructure projects including bridges and commercial skyscrapers. Supervised a team of 4 junior welders.',
        },
        {
          company: 'Beijing Pipeline Services',
          role: 'Pipeline Welder',
          duration: '3 years',
          startDate: '2017-01',
          endDate: '2020-02',
          description:
            'Specialized in cross-country pipeline construction, performing high-pressure welds in field conditions.',
        },
      ],
      education: [
        {
          institution: 'Shanghai Technical Institute',
          degree: 'Diploma',
          field: 'Industrial Welding',
          year: '2016',
        },
      ],
      certifications: [
        {
          name: 'AWS Certified Welder',
          issuer: 'American Welding Society',
          year: '2019',
          validUntil: '2027',
        },
        {
          name: 'ASME IX Certification',
          issuer: 'ASME',
          year: '2020',
          validUntil: '2026',
        },
      ],
    },
    documents: [
      {
        id: 'DOC-5001',
        name: 'Marcus_Chen_Resume.pdf',
        type: 'resume',
        status: 'approved',
        uploadedAt: '2026-06-14T09:25:00Z',
        size: '248 KB',
        adminNotes: 'Resume matches job description. Verified.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5002',
        name: 'Passport_China.pdf',
        type: 'passport',
        status: 'approved',
        uploadedAt: '2026-06-14T09:26:00Z',
        size: '412 KB',
        adminNotes: 'Valid until 2029.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5003',
        name: 'AWS_Certificate.pdf',
        type: 'certificate',
        status: 'pending',
        uploadedAt: '2026-06-14T09:27:00Z',
        size: '156 KB',
        adminNotes: '',
        fileUrl: '#',
      },
      {
        id: 'DOC-5004',
        name: 'Shanghai_Construction_Experience.pdf',
        type: 'experience_letter',
        status: 'pending',
        uploadedAt: '2026-06-14T09:28:00Z',
        size: '324 KB',
        adminNotes: '',
        fileUrl: '#',
      },
    ],
    caseStages: [
      {
        id: 'STG-1',
        label: 'Profile Created',
        status: 'completed',
        completedAt: '2026-06-14T09:23:00Z',
        description: 'Candidate registered through online portal.',
      },
      {
        id: 'STG-2',
        label: 'Documents Uploaded',
        status: 'completed',
        completedAt: '2026-06-14T09:28:00Z',
        description: 'All required documents uploaded.',
      },
      {
        id: 'STG-3',
        label: 'AI Processing',
        status: 'completed',
        completedAt: '2026-06-14T10:05:00Z',
        description: 'Resume processed by AI extraction engine.',
      },
      {
        id: 'STG-4',
        label: 'Admin Review',
        status: 'current',
        completedAt: '',
        description: 'Awaiting admin verification of AI output.',
      },
      {
        id: 'STG-5',
        label: 'Employer Matching',
        status: 'pending',
        completedAt: '',
        description: 'Candidate profile will be matched with employers.',
      },
      {
        id: 'STG-6',
        label: 'Contact Request',
        status: 'pending',
        completedAt: '',
        description: 'Awaiting employer contact request.',
      },
      {
        id: 'STG-7',
        label: 'Visa Assessment',
        status: 'pending',
        completedAt: '',
        description: 'Visa eligibility assessment to be conducted.',
      },
      {
        id: 'STG-8',
        label: 'Final Approval',
        status: 'pending',
        completedAt: '',
        description: 'Final approval and case closure.',
      },
    ],
  },
  {
    id: 'CAND-1025',
    name: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    phone: '+91 98765 43210',
    country: 'India',
    avatarColor: 'bg-emerald-500',
    occupation: 'Registered Nurse',
    skills: ['Critical Care', 'Patient Management', 'IV Therapy', 'Emergency Care'],
    experienceYears: 7,
    education: 'Bachelor of Nursing',
    certifications: ['IELTS 8.0', 'Indian Nursing Council Registration'],
    status: 'approved',
    aiStatus: 'approved',
    caseStatus: 'employer_matching',
    registeredAt: '2026-06-12T14:11:00Z',
    redactedVisible: true,
    aiExtracted: {
      occupation: 'Registered Nurse',
      anzscoCode: '254411',
      anzscoTitle: 'Registered Nurse',
      summary:
        'Compassionate registered nurse with 7 years of critical care experience in hospital settings. Holds a Bachelor of Nursing and demonstrated leadership in emergency departments. Strong communication skills with IELTS 8.0.',
      redactedSummary:
        'Registered nurse with 7 years of critical care experience in hospital settings. Holds a Bachelor of Nursing and demonstrated leadership in emergency departments. Strong communication skills.',
      confidenceScore: 98,
      processedAt: '2026-06-12T15:02:00Z',
      extractedNames: ['Priya Sharma'],
      skills: [
        { name: 'Critical Care', years: 7, proficiency: 'expert' },
        { name: 'Patient Management', years: 7, proficiency: 'expert' },
        { name: 'IV Therapy', years: 6, proficiency: 'advanced' },
        { name: 'Emergency Care', years: 5, proficiency: 'advanced' },
      ],
      experience: [
        {
          company: 'Apollo Hospital Bangalore',
          role: 'Critical Care Nurse',
          duration: '5 years',
          startDate: '2021-04',
          endDate: 'Present',
          description:
            'Responsible for critical care patients in ICU. Managed ventilator settings and assisted in advanced procedures.',
        },
        {
          company: 'Fortis Hospital Delhi',
          role: 'Staff Nurse',
          duration: '2 years',
          startDate: '2019-03',
          endDate: '2021-03',
          description: 'General ward duties, medication administration and patient monitoring.',
        },
      ],
      education: [
        {
          institution: 'Manipal College of Nursing',
          degree: 'Bachelor of Nursing',
          field: 'Nursing',
          year: '2019',
        },
      ],
      certifications: [
        {
          name: 'IELTS 8.0',
          issuer: 'British Council',
          year: '2025',
          validUntil: '2027',
        },
        {
          name: 'Indian Nursing Council Registration',
          issuer: 'INC',
          year: '2019',
          validUntil: 'Lifetime',
        },
      ],
    },
    documents: [
      {
        id: 'DOC-5101',
        name: 'Priya_Sharma_Resume.pdf',
        type: 'resume',
        status: 'approved',
        uploadedAt: '2026-06-12T14:13:00Z',
        size: '210 KB',
        adminNotes: 'Clear, well-formatted. Verified.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5102',
        name: 'Passport_India.pdf',
        type: 'passport',
        status: 'approved',
        uploadedAt: '2026-06-12T14:14:00Z',
        size: '390 KB',
        adminNotes: 'Valid until 2031.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5103',
        name: 'Nursing_Degree_Certificate.pdf',
        type: 'certificate',
        status: 'approved',
        uploadedAt: '2026-06-12T14:15:00Z',
        size: '180 KB',
        adminNotes: 'Degree verified with institution.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5104',
        name: 'Apollo_Experience_Letter.pdf',
        type: 'experience_letter',
        status: 'approved',
        uploadedAt: '2026-06-12T14:16:00Z',
        size: '305 KB',
        adminNotes: 'Signed and stamped.',
        fileUrl: '#',
      },
    ],
    caseStages: [
      {
        id: 'STG-1',
        label: 'Profile Created',
        status: 'completed',
        completedAt: '2026-06-12T14:11:00Z',
        description: 'Candidate registered.',
      },
      {
        id: 'STG-2',
        label: 'Documents Uploaded',
        status: 'completed',
        completedAt: '2026-06-12T14:16:00Z',
        description: 'All documents uploaded.',
      },
      {
        id: 'STG-3',
        label: 'AI Processing',
        status: 'completed',
        completedAt: '2026-06-12T15:02:00Z',
        description: 'AI extraction completed.',
      },
      {
        id: 'STG-4',
        label: 'Admin Review',
        status: 'completed',
        completedAt: '2026-06-13T11:20:00Z',
        description: 'Admin approved AI output.',
      },
      {
        id: 'STG-5',
        label: 'Employer Matching',
        status: 'current',
        completedAt: '',
        description: 'Currently being matched with employers.',
      },
      {
        id: 'STG-6',
        label: 'Contact Request',
        status: 'pending',
        completedAt: '',
        description: 'Awaiting employer.',
      },
      {
        id: 'STG-7',
        label: 'Visa Assessment',
        status: 'pending',
        completedAt: '',
        description: 'Visa assessment pending.',
      },
      {
        id: 'STG-8',
        label: 'Final Approval',
        status: 'pending',
        completedAt: '',
        description: 'Final approval pending.',
      },
    ],
  },
  {
    id: 'CAND-1026',
    name: 'Andrei Popescu',
    email: 'andrei.popescu@email.com',
    phone: '+40 712 345 678',
    country: 'Romania',
    avatarColor: 'bg-violet-500',
    occupation: 'Civil Engineer',
    skills: ['AutoCAD', 'Structural Design', 'Site Management', 'Revit', 'Project Planning'],
    experienceYears: 12,
    education: 'Masters in Civil Engineering',
    certifications: ['EUR-ACE Engineering Certificate', 'Revit Structural Professional'],
    status: 'active',
    aiStatus: 'completed',
    caseStatus: 'ai_processing',
    registeredAt: '2026-06-18T08:42:00Z',
    redactedVisible: false,
    aiExtracted: {
      occupation: 'Civil Engineer',
      anzscoCode: '233211',
      anzscoTitle: 'Civil Engineer',
      summary:
        'Senior civil engineer with 12 years of experience across infrastructure and commercial construction. Strong background in structural design using AutoCAD and Revit. Managed projects valued over $10M in the European market.',
      redactedSummary:
        'Senior civil engineer with 12 years of experience across infrastructure and commercial construction. Strong background in structural design. Managed projects exceeding $10M in value.',
      confidenceScore: 91,
      processedAt: '2026-06-18T09:15:00Z',
      extractedNames: ['Andrei Popescu'],
      skills: [
        { name: 'AutoCAD', years: 12, proficiency: 'expert' },
        { name: 'Structural Design', years: 12, proficiency: 'expert' },
        { name: 'Site Management', years: 10, proficiency: 'advanced' },
        { name: 'Revit', years: 8, proficiency: 'advanced' },
        { name: 'Project Planning', years: 9, proficiency: 'advanced' },
      ],
      experience: [
        {
          company: 'Constructii Bucuresti SA',
          role: 'Senior Civil Engineer',
          duration: '7 years',
          startDate: '2019-05',
          endDate: 'Present',
          description:
            'Lead structural engineer on commercial developments and infrastructure projects. Reviewed and approved structural designs for projects up to $15M.',
        },
        {
          company: 'Infra Romania SRL',
          role: 'Civil Engineer',
          duration: '5 years',
          startDate: '2014-03',
          endDate: '2019-04',
          description: 'Highway and bridge construction. On-site supervision of construction crews.',
        },
      ],
      education: [
        {
          institution: 'Technical University of Civil Engineering Bucharest',
          degree: 'Masters',
          field: 'Civil Engineering',
          year: '2013',
        },
      ],
      certifications: [
        {
          name: 'EUR-ACE Engineering Certificate',
          issuer: 'European Engineering Education',
          year: '2013',
          validUntil: 'Lifetime',
        },
        {
          name: 'Revit Structural Professional',
          issuer: 'Autodesk',
          year: '2022',
          validUntil: '2025',
        },
      ],
    },
    documents: [
      {
        id: 'DOC-5201',
        name: 'Andrei_Popescu_CV.pdf',
        type: 'resume',
        status: 'approved',
        uploadedAt: '2026-06-18T08:44:00Z',
        size: '298 KB',
        adminNotes: 'Detailed CV.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5202',
        name: 'Passport_Romania.pdf',
        type: 'passport',
        status: 'pending',
        uploadedAt: '2026-06-18T08:45:00Z',
        size: '420 KB',
        adminNotes: '',
        fileUrl: '#',
      },
    ],
    caseStages: [
      {
        id: 'STG-1',
        label: 'Profile Created',
        status: 'completed',
        completedAt: '2026-06-18T08:42:00Z',
        description: 'Profile created.',
      },
      {
        id: 'STG-2',
        label: 'Documents Uploaded',
        status: 'completed',
        completedAt: '2026-06-18T08:45:00Z',
        description: '2 of 4 documents uploaded.',
      },
      {
        id: 'STG-3',
        label: 'AI Processing',
        status: 'current',
        completedAt: '',
        description: 'AI extraction completed, awaiting admin.',
      },
      {
        id: 'STG-4',
        label: 'Admin Review',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-5',
        label: 'Employer Matching',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-6',
        label: 'Contact Request',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-7',
        label: 'Visa Assessment',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-8',
        label: 'Final Approval',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
    ],
  },
  {
    id: 'CAND-1027',
    name: 'Maria Santos',
    email: 'maria.santos@email.com',
    phone: '+63 917 123 4567',
    country: 'Philippines',
    avatarColor: 'bg-rose-500',
    occupation: 'Software Developer',
    skills: ['Java', 'Spring Boot', 'React', 'PostgreSQL', 'AWS'],
    experienceYears: 6,
    education: 'Bachelor of Science in Computer Science',
    certifications: ['AWS Certified Developer Associate', 'Spring Professional'],
    status: 'approved',
    aiStatus: 'approved',
    caseStatus: 'final_approval',
    registeredAt: '2026-05-28T11:33:00Z',
    redactedVisible: true,
    aiExtracted: {
      occupation: 'Software Developer',
      anzscoCode: '261312',
      anzscoTitle: 'Developer Programmer',
      summary:
        'Full-stack software developer with 6 years of experience building scalable web applications using Java, Spring Boot, and React. Holds AWS certification. Led a team of 3 developers on a SaaS platform for fintech.',
      redactedSummary:
        'Full-stack software developer with 6 years of experience building scalable web applications. Holds AWS certification. Led a development team on a SaaS platform.',
      confidenceScore: 96,
      processedAt: '2026-05-28T12:10:00Z',
      extractedNames: ['Maria Santos'],
      skills: [
        { name: 'Java', years: 6, proficiency: 'expert' },
        { name: 'Spring Boot', years: 5, proficiency: 'expert' },
        { name: 'React', years: 4, proficiency: 'advanced' },
        { name: 'PostgreSQL', years: 5, proficiency: 'advanced' },
        { name: 'AWS', years: 3, proficiency: 'intermediate' },
      ],
      experience: [
        {
          company: 'Globe Telecom Digital',
          role: 'Senior Software Engineer',
          duration: '3 years',
          startDate: '2023-01',
          endDate: 'Present',
          description:
            'Lead developer for customer billing microservices. Migrated monolith to Spring Boot microservices, reducing latency 40%.',
        },
        {
          company: 'Accenture Philippines',
          role: 'Software Engineer',
          duration: '3 years',
          startDate: '2020-02',
          endDate: '2022-12',
          description: 'Built React frontends for enterprise clients. Mentored 2 junior developers.',
        },
      ],
      education: [
        {
          institution: 'University of the Philippines',
          degree: 'Bachelor of Science',
          field: 'Computer Science',
          year: '2020',
        },
      ],
      certifications: [
        {
          name: 'AWS Certified Developer Associate',
          issuer: 'Amazon Web Services',
          year: '2024',
          validUntil: '2027',
        },
        {
          name: 'Spring Professional',
          issuer: 'VMware',
          year: '2023',
          validUntil: '2026',
        },
      ],
    },
    documents: [
      {
        id: 'DOC-5301',
        name: 'Maria_Santos_Resume.pdf',
        type: 'resume',
        status: 'approved',
        uploadedAt: '2026-05-28T11:35:00Z',
        size: '192 KB',
        adminNotes: 'Well-structured.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5302',
        name: 'Passport_Philippines.pdf',
        type: 'passport',
        status: 'approved',
        uploadedAt: '2026-05-28T11:36:00Z',
        size: '385 KB',
        adminNotes: 'Valid.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5303',
        name: 'CS_Degree_Certificate.pdf',
        type: 'certificate',
        status: 'approved',
        uploadedAt: '2026-05-28T11:37:00Z',
        size: '175 KB',
        adminNotes: 'Verified.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5304',
        name: 'Accenture_Experience.pdf',
        type: 'experience_letter',
        status: 'approved',
        uploadedAt: '2026-05-28T11:38:00Z',
        size: '290 KB',
        adminNotes: 'Signed.',
        fileUrl: '#',
      },
    ],
    caseStages: [
      {
        id: 'STG-1',
        label: 'Profile Created',
        status: 'completed',
        completedAt: '2026-05-28T11:33:00Z',
        description: 'Registered.',
      },
      {
        id: 'STG-2',
        label: 'Documents Uploaded',
        status: 'completed',
        completedAt: '2026-05-28T11:38:00Z',
        description: 'All docs uploaded.',
      },
      {
        id: 'STG-3',
        label: 'AI Processing',
        status: 'completed',
        completedAt: '2026-05-28T12:10:00Z',
        description: 'AI completed.',
      },
      {
        id: 'STG-4',
        label: 'Admin Review',
        status: 'completed',
        completedAt: '2026-05-30T09:40:00Z',
        description: 'Admin approved.',
      },
      {
        id: 'STG-5',
        label: 'Employer Matching',
        status: 'completed',
        completedAt: '2026-06-02T14:00:00Z',
        description: 'Matched with employer.',
      },
      {
        id: 'STG-6',
        label: 'Contact Request',
        status: 'completed',
        completedAt: '2026-06-08T10:30:00Z',
        description: 'Employer contact established.',
      },
      {
        id: 'STG-7',
        label: 'Visa Assessment',
        status: 'completed',
        completedAt: '2026-06-18T16:45:00Z',
        description: 'Visa approved.',
      },
      {
        id: 'STG-8',
        label: 'Final Approval',
        status: 'current',
        completedAt: '',
        description: 'Awaiting final sign-off.',
      },
    ],
  },
  {
    id: 'CAND-1028',
    name: 'Joseph Mwangi',
    email: 'joseph.mwangi@email.com',
    phone: '+254 712 345 678',
    country: 'Kenya',
    avatarColor: 'bg-amber-500',
    occupation: 'Electrician',
    skills: ['Industrial Wiring', 'PLC Programming', 'Motor Maintenance', 'Control Systems'],
    experienceYears: 8,
    education: 'Diploma in Electrical Engineering',
    certifications: ['City & Guilds Level 3', 'IEC Wireman License'],
    status: 'rejected',
    aiStatus: 'rejected',
    caseStatus: 'admin_review',
    registeredAt: '2026-06-15T13:50:00Z',
    redactedVisible: false,
    aiExtracted: {
      occupation: 'Electrician (General)',
      anzscoCode: '341111',
      anzscoTitle: 'Electrician (General)',
      summary:
        'Skilled electrician with 8 years industrial experience in motor maintenance and control systems. Holds City & Guilds Level 3 qualification. Some work history gaps detected requiring clarification.',
      redactedSummary:
        'Skilled electrician with 8 years industrial experience in motor maintenance and control systems.',
      confidenceScore: 72,
      processedAt: '2026-06-15T14:20:00Z',
      extractedNames: ['Joseph Mwangi'],
      skills: [
        { name: 'Industrial Wiring', years: 8, proficiency: 'expert' },
        { name: 'PLC Programming', years: 4, proficiency: 'intermediate' },
        { name: 'Motor Maintenance', years: 8, proficiency: 'expert' },
        { name: 'Control Systems', years: 6, proficiency: 'advanced' },
      ],
      experience: [
        {
          company: 'East Africa Power Ltd',
          role: 'Industrial Electrician',
          duration: '5 years',
          startDate: '2019-06',
          endDate: 'Present',
          description: 'Motor maintenance and PLC troubleshooting at power plant.',
        },
        {
          company: 'Nairobi Manufacturing',
          role: 'Electrician',
          duration: '2 years',
          startDate: '2015-03',
          endDate: '2017-08',
          description: 'Maintenance electrician. Note: gap between 2017 and 2019.',
        },
      ],
      education: [
        {
          institution: 'Kenya Polytechnic',
          degree: 'Diploma',
          field: 'Electrical Engineering',
          year: '2014',
        },
      ],
      certifications: [
        {
          name: 'City & Guilds Level 3',
          issuer: 'City & Guilds',
          year: '2015',
          validUntil: 'Lifetime',
        },
        {
          name: 'IEC Wireman License',
          issuer: 'Energy Regulatory Commission',
          year: '2016',
          validUntil: '2026',
        },
      ],
    },
    documents: [
      {
        id: 'DOC-5401',
        name: 'Joseph_Mwangi_Resume.pdf',
        type: 'resume',
        status: 'rejected',
        uploadedAt: '2026-06-15T13:52:00Z',
        size: '185 KB',
        adminNotes: 'Employment gap not explained. Contact candidate for clarification.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5402',
        name: 'Passport_Kenya.pdf',
        type: 'passport',
        status: 'approved',
        uploadedAt: '2026-06-15T13:53:00Z',
        size: '400 KB',
        adminNotes: 'Valid.',
        fileUrl: '#',
      },
    ],
    caseStages: [
      {
        id: 'STG-1',
        label: 'Profile Created',
        status: 'completed',
        completedAt: '2026-06-15T13:50:00Z',
        description: 'Registered.',
      },
      {
        id: 'STG-2',
        label: 'Documents Uploaded',
        status: 'completed',
        completedAt: '2026-06-15T13:53:00Z',
        description: 'Partial upload.',
      },
      {
        id: 'STG-3',
        label: 'AI Processing',
        status: 'completed',
        completedAt: '2026-06-15T14:20:00Z',
        description: 'AI processed with flags.',
      },
      {
        id: 'STG-4',
        label: 'Admin Review',
        status: 'current',
        completedAt: '',
        description: 'Rejected pending clarification.',
      },
      {
        id: 'STG-5',
        label: 'Employer Matching',
        status: 'pending',
        completedAt: '',
        description: 'On hold.',
      },
      {
        id: 'STG-6',
        label: 'Contact Request',
        status: 'pending',
        completedAt: '',
        description: 'On hold.',
      },
      {
        id: 'STG-7',
        label: 'Visa Assessment',
        status: 'pending',
        completedAt: '',
        description: 'On hold.',
      },
      {
        id: 'STG-8',
        label: 'Final Approval',
        status: 'pending',
        completedAt: '',
        description: 'On hold.',
      },
    ],
  },
  {
    id: 'CAND-1029',
    name: 'Aisha Al-Rashid',
    email: 'aisha.alrashid@email.com',
    phone: '+962 79 123 4567',
    country: 'Jordan',
    avatarColor: 'bg-teal-500',
    occupation: 'Accountant',
    skills: ['IFRS', 'Auditing', 'Financial Reporting', 'QuickBooks', 'Taxation'],
    experienceYears: 10,
    education: 'Bachelor of Accounting',
    certifications: ['ACCA', 'CPA Jordan'],
    status: 'active',
    aiStatus: 'processing',
    caseStatus: 'ai_processing',
    registeredAt: '2026-06-20T07:15:00Z',
    redactedVisible: false,
    aiExtracted: {
      occupation: 'Corporate Accountant',
      anzscoCode: '221111',
      anzscoTitle: 'Accountant (General)',
      summary: 'Processing in progress. Awaiting AI extraction.',
      redactedSummary: 'Processing.',
      confidenceScore: 0,
      processedAt: '',
      extractedNames: [],
      skills: [],
      experience: [],
      education: [],
      certifications: [],
    },
    documents: [
      {
        id: 'DOC-5501',
        name: 'Aisha_AlRashid_Resume.docx',
        type: 'resume',
        status: 'pending',
        uploadedAt: '2026-06-20T07:17:00Z',
        size: '88 KB',
        adminNotes: '',
        fileUrl: '#',
      },
    ],
    caseStages: [
      {
        id: 'STG-1',
        label: 'Profile Created',
        status: 'completed',
        completedAt: '2026-06-20T07:15:00Z',
        description: 'Registered.',
      },
      {
        id: 'STG-2',
        label: 'Documents Uploaded',
        status: 'completed',
        completedAt: '2026-06-20T07:17:00Z',
        description: 'Resume uploaded.',
      },
      {
        id: 'STG-3',
        label: 'AI Processing',
        status: 'current',
        completedAt: '',
        description: 'AI extraction in progress.',
      },
      {
        id: 'STG-4',
        label: 'Admin Review',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-5',
        label: 'Employer Matching',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-6',
        label: 'Contact Request',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-7',
        label: 'Visa Assessment',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-8',
        label: 'Final Approval',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
    ],
  },
  {
    id: 'CAND-1030',
    name: 'Carlos Ramirez',
    email: 'carlos.ramirez@email.com',
    phone: '+52 55 1234 5678',
    country: 'Mexico',
    avatarColor: 'bg-cyan-500',
    occupation: 'Chef',
    skills: ['French Cuisine', 'Pastry', 'Menu Development', 'Team Leadership', 'HACCP'],
    experienceYears: 15,
    education: 'Culinary Arts Diploma',
    certifications: ['Le Cordon Bleu', 'ServSafe Certified'],
    status: 'suspended',
    aiStatus: 'approved',
    caseStatus: 'contact_request',
    registeredAt: '2026-05-10T10:00:00Z',
    redactedVisible: true,
    aiExtracted: {
      occupation: 'Chef de Cuisine',
      anzscoCode: '351311',
      anzscoTitle: 'Chef',
      summary:
        'Award-winning chef de cuisine with 15 years of experience in fine dining. Trained at Le Cordon Bleu. Led kitchens in Michelin-rated restaurants. Suspension pending background check update.',
      redactedSummary:
        'Award-winning chef de cuisine with 15 years of experience in fine dining. Trained at Le Cordon Bleu. Led kitchens in Michelin-rated restaurants.',
      confidenceScore: 88,
      processedAt: '2026-05-10T10:35:00Z',
      extractedNames: ['Carlos Ramirez'],
      skills: [
        { name: 'French Cuisine', years: 15, proficiency: 'expert' },
        { name: 'Pastry', years: 12, proficiency: 'expert' },
        { name: 'Menu Development', years: 13, proficiency: 'expert' },
        { name: 'Team Leadership', years: 10, proficiency: 'advanced' },
        { name: 'HACCP', years: 8, proficiency: 'advanced' },
      ],
      experience: [
        {
          company: 'Pujol Mexico City',
          role: 'Sous Chef',
          duration: '5 years',
          startDate: '2021-06',
          endDate: 'Present',
          description: 'Sous chef at Michelin-rated restaurant. Managed 12-person kitchen brigade.',
        },
        {
          company: 'Le Bistro Paris',
          role: 'Chef de Partie',
          duration: '5 years',
          startDate: '2016-01',
          endDate: '2021-05',
          description: 'Pastry and main course preparation at upscale French restaurant.',
        },
      ],
      education: [
        {
          institution: 'Le Cordon Bleu Paris',
          degree: 'Diploma',
          field: 'Culinary Arts',
          year: '2010',
        },
      ],
      certifications: [
        {
          name: 'Le Cordon Bleu',
          issuer: 'Le Cordon Bleu',
          year: '2010',
          validUntil: 'Lifetime',
        },
        {
          name: 'ServSafe Certified',
          issuer: 'National Restaurant Association',
          year: '2023',
          validUntil: '2028',
        },
      ],
    },
    documents: [
      {
        id: 'DOC-5601',
        name: 'Carlos_Ramirez_CV.pdf',
        type: 'resume',
        status: 'approved',
        uploadedAt: '2026-05-10T10:02:00Z',
        size: '232 KB',
        adminNotes: 'Impressive portfolio.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5602',
        name: 'Passport_Mexico.pdf',
        type: 'passport',
        status: 'approved',
        uploadedAt: '2026-05-10T10:03:00Z',
        size: '410 KB',
        adminNotes: 'Valid.',
        fileUrl: '#',
      },
      {
        id: 'DOC-5603',
        name: 'Le_Cordon_Bleu_Certificate.pdf',
        type: 'certificate',
        status: 'approved',
        uploadedAt: '2026-05-10T10:04:00Z',
        size: '160 KB',
        adminNotes: 'Verified.',
        fileUrl: '#',
      },
    ],
    caseStages: [
      {
        id: 'STG-1',
        label: 'Profile Created',
        status: 'completed',
        completedAt: '2026-05-10T10:00:00Z',
        description: 'Registered.',
      },
      {
        id: 'STG-2',
        label: 'Documents Uploaded',
        status: 'completed',
        completedAt: '2026-05-10T10:04:00Z',
        description: 'Docs uploaded.',
      },
      {
        id: 'STG-3',
        label: 'AI Processing',
        status: 'completed',
        completedAt: '2026-05-10T10:35:00Z',
        description: 'AI processed.',
      },
      {
        id: 'STG-4',
        label: 'Admin Review',
        status: 'completed',
        completedAt: '2026-05-12T11:00:00Z',
        description: 'Approved.',
      },
      {
        id: 'STG-5',
        label: 'Employer Matching',
        status: 'completed',
        completedAt: '2026-05-15T09:30:00Z',
        description: 'Matched.',
      },
      {
        id: 'STG-6',
        label: 'Contact Request',
        status: 'current',
        completedAt: '',
        description: 'Employer contact established. Case suspended pending background check.',
      },
      {
        id: 'STG-7',
        label: 'Visa Assessment',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
      {
        id: 'STG-8',
        label: 'Final Approval',
        status: 'pending',
        completedAt: '',
        description: 'Pending.',
      },
    ],
  },
];

export const employerRequests: EmployerRequest[] = [
  {
    id: 'REQ-201',
    employerName: 'Sarah Williams',
    employerCompany: 'BlueSteel Construction Pty Ltd',
    employerEmail: 'sarah.williams@bluesteel.com.au',
    candidateId: 'CAND-1024',
    candidateName: 'Marcus Chen',
    requestDate: '2026-06-19T03:15:00Z',
    status: 'pending',
    message:
      'We have an urgent opening for a structural welder for a commercial tower project in Melbourne. The candidate profile looks suitable. Requesting contact details to discuss.',
  },
  {
    id: 'REQ-202',
    employerName: 'James O\'Brien',
    employerCompany: 'Sydney Health Network',
    employerEmail: 'james.obrien@sydneyhealth.com.au',
    candidateId: 'CAND-1025',
    candidateName: 'Priya Sharma',
    requestDate: '2026-06-18T01:40:00Z',
    status: 'approved',
    message:
      'Critical care nurse position available at our St Vincent\'s campus. Excellent match. Please share contact info.',
  },
  {
    id: 'REQ-203',
    employerName: 'Lisa Park',
    employerCompany: 'BuildRight Engineering',
    employerEmail: 'lisa.park@buildright.co.nz',
    candidateId: 'CAND-1026',
    candidateName: 'Andrei Popescu',
    requestDate: '2026-06-21T22:05:00Z',
    status: 'pending',
    message:
      'Auckland-based commercial development. Need a senior civil engineer to lead structural design. Candidate is currently in AI processing but we want to express early interest.',
  },
  {
    id: 'REQ-204',
    employerName: 'David Cohen',
    employerCompany: 'FinTech Solutions AU',
    employerEmail: 'david.cohen@fintechsolutions.com.au',
    candidateId: 'CAND-1027',
    candidateName: 'Maria Santos',
    requestDate: '2026-06-05T04:20:00Z',
    status: 'approved',
    message:
      'Java/Spring developer needed for billing platform. Candidate profile matches perfectly.',
  },
  {
    id: 'REQ-205',
    employerName: 'Robert Hughes',
    employerCompany: 'Hughes Electrical Contractors',
    employerEmail: 'robert@hugheselectrical.co.nz',
    candidateId: 'CAND-1028',
    candidateName: 'Joseph Mwangi',
    requestDate: '2026-06-17T08:10:00Z',
    status: 'rejected',
    message:
      'Looking for industrial electrician. Request denied due to candidate profile issues per admin review.',
  },
  {
    id: 'REQ-206',
    employerName: 'Margaret Foster',
    employerCompany: 'The Harbour Restaurant Group',
    employerEmail: 'margaret.foster@harbourgroup.com.au',
    candidateId: 'CAND-1030',
    candidateName: 'Carlos Ramirez',
    requestDate: '2026-06-02T00:30:00Z',
    status: 'pending',
    message:
      'Executive Chef opening at our flagship Melbourne fine dining venue. Candidate\'s Le Cordon Bleu credentials are highly attractive.',
  },
];

export const notifications: NotificationItem[] = [
  {
    id: 'N-101',
    type: 'employer_request_received',
    title: 'New Employer Request',
    description:
      'Lisa Park from BuildRight Engineering submitted a contact request for Andrei Popescu.',
    timestamp: '2026-06-21T22:05:00Z',
    read: false,
  },
  {
    id: 'N-102',
    type: 'ai_processing_completed',
    title: 'AI Processing Completed',
    description:
      'AI extraction for Marcus Chen (CAND-1024) completed with 94% confidence.',
    timestamp: '2026-06-14T10:05:00Z',
    read: false,
  },
  {
    id: 'N-103',
    type: 'document_approval_required',
    title: 'Document Approval Required',
    description:
      '2 documents from Marcus Chen require review before AI output approval.',
    timestamp: '2026-06-14T09:28:00Z',
    read: false,
  },
  {
    id: 'N-104',
    type: 'candidate_registered',
    title: 'New Candidate Registered',
    description: 'Aisha Al-Rashid from Jordan created a profile.',
    timestamp: '2026-06-20T07:15:00Z',
    read: true,
  },
  {
    id: 'N-105',
    type: 'candidate_approved',
    title: 'Candidate Approved',
    description: 'Priya Sharma was approved by admin reviewer.',
    timestamp: '2026-06-13T11:20:00Z',
    read: true,
  },
  {
    id: 'N-106',
    type: 'employer_request_received',
    title: 'New Employer Request',
    description: 'Sarah Williams from BlueSteel Construction requested Marcus Chen.',
    timestamp: '2026-06-19T03:15:00Z',
    read: true,
  },
  {
    id: 'N-107',
    type: 'ai_processing_completed',
    title: 'AI Processing Started',
    description: 'AI extracting information from Aisha Al-Rashid\'s resume.',
    timestamp: '2026-06-20T07:17:00Z',
    read: true,
  },
  {
    id: 'N-108',
    type: 'case_stage_updated',
    title: 'Case Stage Updated',
    description: 'Maria Santos advanced to Final Approval stage.',
    timestamp: '2026-06-18T16:45:00Z',
    read: true,
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'LOG-5001',
    user: 'admin.sarah@migrateflow.io',
    action: 'Approved AI output for candidate Marcus Chen',
    target: 'CAND-1024',
    timestamp: '2026-06-14T10:30:00Z',
    category: 'ai',
  },
  {
    id: 'LOG-5002',
    user: 'admin.sarah@migrateflow.io',
    action: 'Approved document "Priya_Sharma_Resume.pdf"',
    target: 'DOC-5101',
    timestamp: '2026-06-12T14:30:00Z',
    category: 'document',
  },
  {
    id: 'LOG-5003',
    user: 'admin.james@migrateflow.io',
    action: 'Approved employer request from Sydney Health Network',
    target: 'REQ-202',
    timestamp: '2026-06-18T02:00:00Z',
    category: 'employer',
  },
  {
    id: 'LOG-5004',
    user: 'admin.sarah@migrateflow.io',
    action: 'Rejected document "Joseph_Mwangi_Resume.pdf" — requested re-upload',
    target: 'DOC-5401',
    timestamp: '2026-06-15T15:00:00Z',
    category: 'document',
  },
  {
    id: 'LOG-5005',
    user: 'admin.james@migrateflow.io',
    action: 'Updated case stage for Maria Santos to Final Approval',
    target: 'CAND-1027',
    timestamp: '2026-06-18T16:45:00Z',
    category: 'candidate',
  },
  {
    id: 'LOG-5006',
    user: 'admin.sarah@migrateflow.io',
    action: 'Registered new candidate Aisha Al-Rashid',
    target: 'CAND-1029',
    timestamp: '2026-06-20T07:15:00Z',
    category: 'candidate',
  },
  {
    id: 'LOG-5007',
    user: 'system',
    action: 'AI extraction job started for Aisha Al-Rashid',
    target: 'CAND-1029',
    timestamp: '2026-06-20T07:17:00Z',
    category: 'ai',
  },
  {
    id: 'LOG-5008',
    user: 'admin.james@migrateflow.io',
    action: 'Suspended candidate Carlos Ramirez pending background check',
    target: 'CAND-1030',
    timestamp: '2026-06-16T14:10:00Z',
    category: 'candidate',
  },
  {
    id: 'LOG-5009',
    user: 'admin.sarah@migrateflow.io',
    action: 'Rejected AI output for Joseph Mwangi due to confidence concerns',
    target: 'CAND-1028',
    timestamp: '2026-06-15T15:20:00Z',
    category: 'ai',
  },
  {
    id: 'LOG-5010',
    user: 'admin.james@migrateflow.io',
    action: 'Approved employer request from FinTech Solutions AU',
    target: 'REQ-204',
    timestamp: '2026-06-05T05:00:00Z',
    category: 'employer',
  },
  {
    id: 'LOG-5011',
    user: 'admin.sarah@migrateflow.io',
    action: 'Updated admin notes on document "Marcus_Chen_Resume.pdf"',
    target: 'DOC-5001',
    timestamp: '2026-06-14T09:45:00Z',
    category: 'document',
  },
  {
    id: 'LOG-5012',
    user: 'system',
    action: 'Scheduled nightly AI model retraining job',
    target: 'SYSTEM',
    timestamp: '2026-06-19T22:00:00Z',
    category: 'system',
  },
];

export const recentActivities: Activity[] = [
  {
    id: 'ACT-01',
    type: 'candidate_registered',
    description: 'New candidate Aisha Al-Rashid registered from Jordan',
    timestamp: '2026-06-20T07:15:00Z',
    actor: 'System',
    icon: 'user',
  },
  {
    id: 'ACT-02',
    type: 'ai_processing',
    description: 'AI processed resume for Andrei Popescu with 91% confidence',
    timestamp: '2026-06-18T09:15:00Z',
    actor: 'AI Engine',
    icon: 'ai',
  },
  {
    id: 'ACT-03',
    type: 'candidate_approved',
    description: 'Priya Sharma was approved by admin',
    timestamp: '2026-06-13T11:20:00Z',
    actor: 'admin.sarah',
    icon: 'approve',
  },
  {
    id: 'ACT-04',
    type: 'employer_request',
    description:
      'BlueSteel Construction submitted a contact request for Marcus Chen',
    timestamp: '2026-06-19T03:15:00Z',
    actor: 'Sarah Williams',
    icon: 'employer',
  },
  {
    id: 'ACT-05',
    type: 'ai_processing',
    description: 'AI extraction completed for Marcus Chen — 94% confidence',
    timestamp: '2026-06-14T10:05:00Z',
    actor: 'AI Engine',
    icon: 'ai',
  },
  {
    id: 'ACT-06',
    type: 'candidate_registered',
    description: 'New candidate Joseph Mwangi registered from Kenya',
    timestamp: '2026-06-15T13:50:00Z',
    actor: 'System',
    icon: 'user',
  },
  {
    id: 'ACT-07',
    type: 'employer_request',
    description: 'Sydney Health Network requested Priya Sharma contact details',
    timestamp: '2026-06-18T01:40:00Z',
    actor: 'James O\'Brien',
    icon: 'employer',
  },
];

export function getCandidateById(id: string): Candidate | undefined {
  return candidates.find((c) => c.id === id);
}
